/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Main": "主界面",
    "Incremental": "增量",
    "Gods of Incremental Server": "增量服务器之神",
    "loop=true hidden=true autostart=true": "循环=true 隐藏=true 自动开始=true",
    "Point Powerer": "点数力量",
    "Point Processor": "点数处理器",
    "Point Producer": "点数生产者",
    "This is just an ordinary game.": "这只是一个普通的游戏。",
    "This is the blank canvas for any incremental game.": "这是任何增量游戏的空白画布。",
    "This is the framework for much better games.": "这是更好的游戏的框架。",
    "Mute": "静音",
    "Unmute": "播放",
    "on reset.": "在重置时。",
    "Prestige": "声望",
    "Incremental power was the strongest form of power, now it's barely passing.": "增量力量曾经是最强的力量，现在已经勉强过关了。",
    "Prestige for prestige points": "声望以获得声望点",
    "Prestige Point Buyable": "声望点数可购买",
    "prestige points.": "声望点数。",
    "Unlocks a new layer": "解锁一个新层",
    "Incremental Power": "增量力量",
    "Meta-Prestige": "元声望",
    "Pathless Factors": "无路因子",
    "Score Breakdown": "分数明细",
    "Standard Path Activator": "标准路径激活器",
    "Unlocks activation for the standard path.": "解锁标准路径的激活。",
    "Upgrades": "升级",
    "Boosts points based on unspent incremental power.": "根据未使用的 增量力量 来提升 点数。",
    "After THEY took everything from us, nothing was the same.": "当他们夺走了我们的一切之后，一切都不再一样了。",
    "CHAPTER 1: THE STANDARD PATH.": "第一章：标准路径。",
    "I'm going to ask you a question. What are you doing here?": "我要问你一个问题。 你在这里做什么？",
    "Incrementals aren't as great as they were before.": "增量不如以前那么大。",
    "THE DEATH REALM took everything. It's all over.": "死亡王国夺走了一切。 一切都结束了。",
    "The incremental power didn't work as well. We were all doomed.": "增量力量并没有发挥同样的作用。 我们都注定了。",
    "There is no point of restoring the balance of incrementals.": "恢复增量平衡是没有意义的。",
    "Automatically buys main buyables without spending points.": "自动购买主要可购买物品，无需花费点数。",
    "Boosts points based on prestige points.": "根据声望点数提升点数。",
    "Energy": "能量",
    "Energy Extractor": "能量提取器",
    "prestige energy per second.": "每秒声望能量。",
    "prestige energy.": "声望能量。",
    "Standard Path Effects:": "标准路径效果：",
    "Start Producing": "开始生产",
    "Stop Producing": "停止生产",
    "This should make incremental power stronger.": "这应该会让增量力量变得更强。",
    "Unlocks machines.": "解锁机器。",
    "After many failed attempts. The path of singularity. The game developer.": "经过多次失败的尝试。 独特之路。 游戏开发商。",
    "All attempts to produce a perfect hero.": "所有的努力都是为了塑造一个完美的英雄。",
    "Create a prestige machine.": "创造一台声望机器。",
    "However, there are some corrupted energies in it.": "然而，其中却蕴藏着一些腐化的能量。",
    "I am no being of incremental power, as I am from a foreign realm.": "我并不是拥有增量力量的存在，因为我来自异域。",
    "I am not one of the four nobles, but I work with them.": "我不是四贵族之一，但我和他们一起工作。",
    "I am not the greatest at giving directions.": "我并不是最擅长给出指示的人。",
    "I want to make sure no hero loses to celestial powers.": "我想确保没有英雄会输给天体力量。",
    "If you have made contact with Yhvr, follow his directions.": "如果您已与 Yhvr 取得联系，请按照他的指示进行操作。",
    "Last time it didn't go so well.": "上次没那么顺利。",
    "machine corruption.": "机器腐败。",
    "Machines": "机器",
    "Maybe you do have a reason to be here.": "也许你确实有理由来这里。",
    "Me and my team worked very hard to create a path like this.": "我和我的团队非常努力地创造了一条这样的道路。",
    "My name is Red Diamond. I am from THE HIGHER PLANE OF EXISTENCE.": "我的名字是红钻石。 我来自更高的存在平面。",
    "Oh shoot! I just realized!": "哦，射击！ 我才发现！",
    "Platonic! The corruptions! The path of ascension!": "柏拉图式的！ 腐败！ 飞升之路！",
    "prestige machines.": "声望机器。",
    "That yellow glow...": "那黄色的光芒...",
    "The standard path. The easiest one to master.": "标准路径。 最容易掌握的一种。",
    "They will provide a good booster and help with meta-prestiges.": "他们将提供良好的助推器并帮助提升元声望。",
    "Unlike the last one...": "与上一个不同的是...",
    "WHY DID I BRING THEM OVER TO THIS PATH...": "我为什么要带他们走上这条路……",
    "Yhvr was right. Maybe a simpler path is the way to start.": "Yhvr 是对的。 也许一条更简单的道路是开始的方式。",
    "YOU CANNOT REFUND MACHINES. THE CORRUPTION IS INEVITABLE.": "您无法为机器退款。 腐败是不可避免的。",
    "You must be the hero! I will introduce myself.": "你一定是英雄！ 我会介绍我自己。",
    "Your job now should be to produce prestige machines.": "你现在的工作应该是生产名牌机器。",
    "Unlocks a pathless factor.": "解锁一个无路因子。",
    "Boosts prestige points based on unspent incremental power.": "根据未使用的增量力量提升声望点数。",
    "Pure Energy": "纯粹能量",
    "Unlocks the pure energy feature.": "解锁纯粹能量功能。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Factor I": "因子 I",
    "Factor II": "因子 II",
    "Boost II": "提升 II",
    "Boost I": "提升 I",
    "SP Prestige Upgrade I": "SP 声望升级 I",
    "SP Prestige Upgrade II": "SP 声望升级 II",
    "SP Prestige Upgrade III": "SP 声望升级 III",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "The Incremental God Tree\n\t\t\t\t\t\t\tDiscord": "The Incremental God Tree\n\t\t\t\t\t\t\tDiscord",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "TOTAL SCORE: ": "总分数: ",
    "YOUR SCORE: ": "你的分数: ",
    "Your machines cause there to be ": "你的机器导致有 ",
    "Current corruption delay: ": "当前腐败延迟：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " to points.": " 到点数。",
    " to prestige points.": " 到声望点数。",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\/([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\(([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) points per second.$/, '你每秒获得 $1 点数。'],
    [/^which are boosting points by x(.+).\n(.+)Cost: (.+) Prestige Points$/, '提升点数 x$1。\n 成本：$3 声望点数'],
    [/^which are boosting points by x(.+).\n(.+)Cost: (.+) Points$/, '提升点数 x$1。\n 成本：$3 点数'],
    [/^which are producing (.+) points per second.\n(.+)Cost: (.+) Points$/, '每秒生产 $1 点数。\n 成本：$3 点数'],
    [/^which are producing (.+) prestige Energy per second.\n(.+)Cost: (.+) Prestige Points$/, '每秒生产 $1 声望能量。\n 成本：$3 声望点数'],
    [/^which are producing (.+) prestige energy per second.\n(.+)Cost: (.+) Prestige Points$/, '每秒生产 $1 声望能量。\n 成本：$3 声望点数'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) points.$/, '你有 $1 点数。'],
    [/^You have (.+) incremental energy.$/, '你有 $1 增量能量。'],
    [/^You have (.+) incremental power.$/, '你有 $1 增量力量。'],
    [/^Your incremental energy give a (.+) boost to points and prestige energy.$/, '您的 增量力量 可以使 点数 和 声望能量 提升 $1。'],
    [/^Your prestige machines will give you (.+) incremental energy on reset.$/, '您的声望机器将在重置时为您提供 $1 增量能量。'],
    [/^which gives a (.+) boost to prestige points gain.$/, '这使得声望点数增益提高了 $1。'],
    [/^You are gaining (.+)$/, '你获得 $1'],
    [/^but a (.+) divide on point gain.$/, '但点数增益 $1。'],
    [/^Best prestige energy: (.+)$/, '最佳声望能量：$1'],
    [/^Time played: (.+)$/, '游戏时长：$1'],
    [/^You have (.+)$/, '你有 $1'],
    [/^Best points: (.+) base score$/, '最佳分数：$1 基础分数'],
    [/^Activate the standard path \(Req: (.+) PP\)$/, '激活标准路径（要求：$1 声望点数）'],
    [/^LEARN YOUR TRUE PURPOSE \(Req: (.+) PP\)$/, '了解您的真正目的（要求：$1 声望点数）'],
    [/^Next at (.+) score$/, '下一个在 $1 分数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^which causes the prestige energy downside to be (.+) stronger.$/, '这会导致声望能量的负面影响增强 $1。'],
    [/^which gives a (.+) boost to prestige energy and prestige point gain.$/, '这使声望能量和声望点数增益提高了 $1。'],
    [/^You will gain (.+)$/, '你会获得 $1'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^\+(.+) PP$/, '\+$1 声望点数'],
    [/^Cost: (.+) Prestige Points$/, '成本：$1 声望点数'],
    [/^Cost: (.+) Incremental Power$/, '成本：$1 增量力量'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) prestige points.$/, '要求：$1 声望点数。'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
    [/^(.+) Incremental Power$/, '$1 增量力量'],

]);